version: "3.9"

services:
  api:
    build: ./server
    container_name: api_doacoes
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      - db
    restart: always

  client:
    build: ./client
    container_name: front_doacoes
    ports:
      - "80:80"
    depends_on:
      - api
    restart: always

  db:
    image: mariadb:latest
    container_name: mariadb_doacoes
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: doacoes
      MYSQL_USER: riobonito
      MYSQL_PASSWORD: ajudariobonito2025
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
